// src/components/CategoryNav.tsx
export default function CategoryNav({ categories, selectedCategory, onSelectCategory }) {
  return (
    <nav className="bg-white shadow-sm sticky top-0 z-10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex gap-2 overflow-x-auto py-4 scrollbar-hide">
          <button
            onClick={() => onSelectCategory(null)}
            className={`px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap transition-all duration-200 ${
              selectedCategory === null
                ? "bg-gradient-to-r from-indigo-500 to-purple-500 text-white shadow-md"
                : "bg-gray-100 text-gray-600 hover:bg-gray-200"
            }`}
          >
            全部
          </button>
          {categories.map((category) => (
            <button
              key={category.id}
              onClick={() => onSelectCategory(category.id)}
              className={`px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap transition-all duration-200 flex items-center gap-2 ${
                selectedCategory === category.id
                  ? "bg-gradient-to-r from-indigo-500 to-purple-500 text-white shadow-md"
                  : "bg-gray-100 text-gray-600 hover:bg-gray-200"
              }`}
            >
              <span className="text-lg">{category.icon}</span>
              <span>{category.name}</span>
            </button>
          ))}
        </div>
      </div>
    </nav>
  );
}

// src/components/CategoryNav.vue
<script setup lang="ts">
import { inject, type Ref } from 'vue';
import type { Category } from '../data/emojis';

interface SkinColorItem {
  id: string;
  name: string;
  gradient: string;
}

defineProps<{
  categories: Category[];
  selectedCategory: string | null;
}>();

const emit = defineEmits<{
  select: [categoryId: string | null];
}>();

const skinColor = inject<Ref<string>>('skinColor')!;
const skinColors = inject<SkinColorItem[]>('skinColors')!;

const handleSelect = (categoryId: string | null) => {
  emit('select', categoryId);
};
</script>

<template>
  <div class="flex flex-wrap gap-2 mt-4">
    <button
      @click="handleSelect(null)"
      :class="[
        'px-4 py-2 rounded-full text-sm font-medium transition-all duration-200',
        selectedCategory === null
          ? 'text-white shadow-md'
          : 'bg-white text-gray-600 hover:bg-gray-100 border border-gray-200'
      ]"
      :style="selectedCategory === null ? { backgroundColor: `var(--skin-color, #6366f1)` } : {}"
    >
      全部
    </button>
    
    <button
      v-for="category in categories"
      :key="category.id"
      @click="handleSelect(category.id)"
      :class="[
        'px-4 py-2 rounded-full text-sm font-medium transition-all duration-200 flex items-center gap-2',
        selectedCategory === category.id
          ? 'text-white shadow-md'
          : 'bg-white text-gray-600 hover:bg-gray-100 border border-gray-200'
      ]"
      :style="selectedCategory === category.id ? { backgroundColor: `var(--skin-color, #6366f1)` } : {}"
    >
      <span>{{ category.icon }}</span>
      {{ category.name }}
    </button>
  </div>
</template>
